### ISSUE TITLE
Rider Registration Form Fields

### ISSUE THREAD

**Issue by komenAnna** [SongaBiz/Songa-webpage#20]
We have a multistep form, each step the rider is required to fill in the following fields:
**Step 1: RIDER DETAILS**
first_name: string;
last_name: string;
password: string;
phone_no: string;
confirmPassword: string;

**Step 2: RIDER PROFILE**
location: string;
stage_name: string;
town_of_operation: string;
gender: string;
job_type (public or private): string;

**Step 3: BIKE DETAILS**
type: string;
model: string;
plate_no: string;
insurance_provider? (yes or no): string;

**Step 4: UPLOAD IMAGES --  KYC**
ID_front: null,
ID_back: null,
license_front: null,
license_back: null

**Step 5: PREVIEW**
first_name: string;
last_name: string;
password: string;
confirmPassword: string;
phone_no: string;
ID_front: any;
ID_back: any;
license_front: any;
license_back: any;
insurance: any;
type: string;
model: string;
plate_no: string;
insurance_provider: string;
insurance_policy_no: string;

**Comment by wilfex81** [comment]
backend models set up
